---
title: "StreetEvents updates"
author: "Ian Gow"
date: "May 3, 2016"
output: 
    pdf_document:
        fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## StreetEvents update

```{r data_step, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(scales)

pg <- src_postgres(host="iangow.me", dbname="crsp")

calls <- tbl(pg, sql("SELECT * FROM streetevents.calls"))
speaker_data <- tbl(pg, sql("SELECT * FROM streetevents.speaker_data"))
call_files<- tbl(pg, sql("SELECT * FROM streetevents.call_files"))
```

```{r most_recent}
calls %>%
    select(last_update) 
```

```{r call_date, message=FALSE, fig.cap="Histogram of `call_date` on `calls`"}
calls %>%
    filter(file_path ~ 'Jun2016') %>%
    mutate(call_month=date_trunc('month', call_date)) %>%
    select(call_month) %>%
    as.data.frame() %>%
    ggplot(aes(x=call_month)) +
    geom_histogram()
```

```{r last_update, message=FALSE, fig.cap="Histogram of `last_update` on `calls`"}
calls %>%
    filter(file_path ~ 'Jun2016') %>%
    as.data.frame() %>%
    ggplot(aes(x=last_update)) +
    geom_histogram()
```

```{r last_update_speaker, message=FALSE, fig.cap="Histogram of `last_update` on `speaker_data`"}
speaker_data %>%
    filter(last_update > '2016-05-31') %>%
    select(file_name, last_update) %>%
    distinct() %>%
    as.data.frame() %>%
    ggplot(aes(x=last_update)) +
    geom_histogram()
```

```{r mtime, message=FALSE, fig.cap="Histogram of `mtime` on `call_files`"}
call_files %>%
    filter(file_path ~ 'Jun2016') %>%
    as.data.frame() %>%
    ggplot(aes(x=mtime)) +
    geom_histogram()
```
